### PR TITLE
Fix #136

### LINKED ISSUE #136: [Python] Deal with a breaking change
The changes produced in PR #110 break existing behavior and public APIs. [Attributes with no leading underscores are considered public API.](https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables)

Related: #134 @shniubobo 

### Difference

Formerly ( ef67d36 ):
```
$ ipython
Python 3.8.2 (default, May 22 2020, 21:44:03)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import RADWIMPS

In [2]: RADWIMPS.RADWIMPS.then().then().then().世()
前前前世
Out[2]: RADWIMPS.RADWIMPS

In [3]:
Do you really want to exit ([y]/n)? y
$
```

And now ( 7cbc601 ):
```
$ ipython
Python 3.8.2 (default, May 22 2020, 21:44:03)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import RADWIMPS

In [2]: RADWIMPS.RADWIMPS.then().then().then().世()
Out[2]: 前前前<coroutine object RADWIMPS.世 at 0x106eb48c0>

In [3]:
Do you really want to exit ([y]/n)? y
/Users/takumi/.pyenv/versions/3.8.2/lib/python3.8/site-packages/IPython/core/interactiveshell.py:1445: RuntimeWarning: coroutine 'RADWIMPS.世' was never awaited
  self.user_ns_hidden.clear()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

 - No `print()` on invocation of `RADWIMPS.then()`
 - Returns a coroutine instead of `RADWIMPS.RADWIMPS`
 - Python scolds us on exit

This kind of change will confuse the users of the `RADWIMPS` module as it is not intended to return async stuff. While it is a joke repository, breaking changes should be carefully considered and avoided.

### Improvement

Async APIs are worth having. Forking `RADWIMPS.py` should solve this issue and rolls back to the code it ought to be. While async modules are named like `asyncfoobar.py` in general, it's better to name it `RADWIMPS_async.py` here.

```
$ cp RADWIMPS.py RADWIMPS_async.py  # queer capitalizing tho ;)
$ git revert 7cbc601
$ git add RADWIMPS_async.py
$ git commit -m "blahblah"
```

### PR DESCRIPTION
**Pull request by shniubobo**
Fix #136 by reverting 7cbc601 and forking `RADWIMPS.py`.

Thanks to the solution provided by @puhitaku.

### CODE REVIEW

**Comment by siketyan** [comment]
@puhitaku @shniubobo 
Thank you for the issue and PR.
We'd like to use the same name `RADWIMPS` through all languages, so could you rename `RADWIMPS_async.py` to `RADWIMPS.async.py` ?

**Comment by shniubobo** [comment]
> @puhitaku @shniubobo
> Thank you for the issue and PR.
> We'd like to use the same name `RADWIMPS` through all languages, so could you rename `RADWIMPS_async.py` to `RADWIMPS.async.py` ?

~~Yes, sure.~~

Edit:
Sorry I didn't notice that a module cannot be named with `.` in it in Python. Thanks to @puhitaku.

**Comment by puhitaku** [comment]
Unfortunately, that's impossible. Priod is not allowed to name a module as it's the delimiter of module structure.

```
$ ls *.py
RADWIMPS.async.py  RADWIMPS.py
```

```
$ ipython
Python 3.8.2 (default, May 22 2020, 21:44:03)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import RADWIMPS.async
  File "<ipython-input-1-216437762f5d>", line 1
    import RADWIMPS.async
                    ^
SyntaxError: invalid syntax


In [2]: import importlib

In [3]: ra = importlib.import_module('RADWIMPS.async')
前前前世
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-716f24d7cac0> in <module>
----> 1 ra = importlib.import_module('RADWIMPS.async')

~/.pyenv/versions/3.8.2/lib/python3.8/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128
    129

~/.pyenv/versions/3.8.2/lib/python3.8/importlib/_bootstrap.py in _gcd_import(name, package, level)

~/.pyenv/versions/3.8.2/lib/python3.8/importlib/_bootstrap.py in _find_and_load(name, import_)

~/.pyenv/versions/3.8.2/lib/python3.8/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'RADWIMPS.async'; 'RADWIMPS' is not a package

In [4]: RADWIMPS
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-245e56a773ca> in <module>
----> 1 RADWIMPS

NameError: name 'RADWIMPS' is not defined
```

**Comment by puhitaku** [comment]
Ah now I remember the original goal; show "前前前世" with code like `then().then().then().世()`. Importing won't be a problem in that situation where we run the single script like `python RADWIMPS.async.py`. Please proceed 👍

**Comment by shniubobo** [comment]
> Ah now I remember the original goal; show "前前前世" with code like `then().then().then().世()`. Importing won't be a problem in that situation where we run the single script like `python RADWIMPS.async.py`. Please proceed 👍

That's all right. I will restore c08f3f4 then.

**Review by siketyan — APPROVED** [review]

**Review by MikuroXina — APPROVED** [review]

**Pull request merged**
