### PR TITLE
Make use of Future in Python

### PR DESCRIPTION
**Pull request by shniubobo**
Please see https://github.com/approvers/RADWIMPS/pull/110#issuecomment-656823506 for more details.

I'm not sure whether this commit is better or not. Although it better follows the rules, the code is more complicated since `Future` is a low-level API of `asyncio`.

### CODE REVIEW

**Comment by shniubobo** [comment]
Suspending due to #136.

**Comment by shniubobo** [comment]
Reopening after the resolution of #136.

**Comment by siketyan** [comment]
Could you rebase the branch onto `master` ?

**Comment by shniubobo** [comment]
> Could you rebase the branch onto `master` ?

Since the branch had been made public before a rebase became necessary, I thought it would be better to do a merge rather than a rebase to avoid rewriting the history. But if rebasing is preferred anyway, I can revert 9f1f560 and do so instead.

**Comment by shniubobo** [comment]
In case it is needed, these changes were applied to the branch `shniubobo:improve-py` during the force-push:
```
git reset 0529e5f --hard
git rebase --onto master improve-py~2 improve-py
```

**Review by siketyan — APPROVED** [review]

**Review by MikuroXina — APPROVED** [review]

**Pull request merged**
